### ISSUE TITLE
Diamond Shop songs get locked when using FuserSongLoader

### ISSUE THREAD

**Issue by polocatfan** [Mettra/FuserSongLoader#2]
removing winhttp.dll unlocks the diamond shop songs.
adding it back locks them.

**Comment by Mettra** [comment]
Yeah, this is an issue with `winhttp.dll` being the file used to hook, although I'm not entirely sure why it disables all networking for the game. It used to sorta be a feature, since I didn't want to step on any toes with Harmonix. I'm sure another file could be used, but I don't know when I will revisit this codebase.

**Comment by polocatfan** [comment]
I found a kind of fix for this. Removing the dll and adding diamond shop songs to a crate then adding the dll back lets you use diamond shop songs.

**Comment by polocatfan** [comment]
someone fixed it https://github.com/NarrikSynthfox/FuserSongLoader/releases/tag/diamond_shop_fix
